[package]
name = "aurora"
version = "0.1.0"
edition = "2024"

[dependencies]
annotate-snippets = "0.12.8"
clap = { version = "4.5.51", features = ["derive"] }
indexmap = "2.12.0"
reqwest = { version = "0.12.24", features = ["blocking"] }
serde_json = "1.0.145"
